quick_sort_pivot_first_element: quick_sort_pivot_first_element.c
	$(CC) quick_sort_pivot_first_element.c -o quick_sort_pivot_first_element

clean: 
	$(RM) quick_sort_pivot_first_element

run: clean quick_sort_pivot_first_element
	./quick_sort_pivot_first_element